/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Sale = {
  _id: string;
  _type: "sale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  discountAmount?: number;
  couponCode?: string;
  validFrom?: string;
  validUntil?: string;
  isActive?: boolean;
};

export type Orders = {
  _id: string;
  _type: "orders";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripeCheckoutSessionId?: string;
  stripePaymentIntentId?: string;
  stripeCustomerId?: string;
  shippingAddress?: {
    fullName?: string;
    street1?: string;
    street2?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
    phone?: string;
  };
  products?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity?: number;
    selectedColor?: string;
    selectedSize?: string;
    _key: string;
  }>;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  status?: "pending" | "paid" | "shipped" | "delivered" | "cancelled";
  orderDate?: string;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: BlockContent;
  price?: number;
  discountPercentage?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  variants?: Array<{
    colorName?: string;
    colorImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    stock?: number;
    sizes?: Array<{
      size?: string;
      stock?: number;
      _key: string;
    }>;
    _type: "colorVariant";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Sale | Orders | BlockContent | Category | SanityImageCrop | SanityImageHotspot | Slug | Product | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/orders/getMyOrders.ts
// Variable: MY_ORDERS_QUERY
// Query: *[_type == "orders" && clerkUserId == $userId]      | order(orderDate desc) {        _id,        orderNumber,        clerkUserId,        customerName,        email,        stripeCheckoutSessionId,        stripePaymentIntentId,        stripeCustomerId,        currency,        status,        totalPrice,        amountDiscount,        orderDate,          shippingAddress {          fullName,          street1,          street2,          city,          state,          postalCode,          country,          phone        },          products[] {          quantity,          selectedColor,          selectedSize,          product->{            _id,            name,            price,            image,            "slug": slug.current,            variants          }        }      }
export type MY_ORDERS_QUERYResult = Array<{
  _id: string;
  orderNumber: string | null;
  clerkUserId: string | null;
  customerName: string | null;
  email: string | null;
  stripeCheckoutSessionId: string | null;
  stripePaymentIntentId: string | null;
  stripeCustomerId: string | null;
  currency: string | null;
  status: "cancelled" | "delivered" | "paid" | "pending" | "shipped" | null;
  totalPrice: number | null;
  amountDiscount: number | null;
  orderDate: string | null;
  shippingAddress: {
    fullName: string | null;
    street1: string | null;
    street2: string | null;
    city: string | null;
    state: string | null;
    postalCode: string | null;
    country: string | null;
    phone: string | null;
  } | null;
  products: Array<{
    quantity: number | null;
    selectedColor: string | null;
    selectedSize: string | null;
    product: {
      _id: string;
      name: string | null;
      price: number | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      slug: string | null;
      variants: Array<{
        colorName?: string;
        colorImage?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        stock?: number;
        sizes?: Array<{
          size?: string;
          stock?: number;
          _key: string;
        }>;
        _type: "colorVariant";
        _key: string;
      }> | null;
    } | null;
  }> | null;
}>;

// Source: ./sanity/lib/products/getAllCategories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[_type == "category"] | order(name asc)
export type ALL_CATEGORIES_QUERYResult = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;

// Source: ./sanity/lib/products/getAllProducts.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type == "product"] | order(name asc){      _id,      name,      slug,      price,      discountPercentage,      image,      variants[]{        colorName,        colorImage{          asset->{ _id, url }        },        stock,        sizes[]{          size,          stock        }      }    }
export type ALL_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  discountPercentage: number | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  variants: Array<{
    colorName: string | null;
    colorImage: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
    stock: number | null;
    sizes: Array<{
      size: string | null;
      stock: number | null;
    }> | null;
  }> | null;
}>;

// Source: ./sanity/lib/products/getProductByCategory.ts
// Variable: PRODUCTS_BY_CATEGORY_QUERY
// Query: *[_type == "product" && references(*[_type == "category" && slug.current == $slug]._id)]    | order(name asc){      _id,      name,      slug,      price,      discountPercentage,      image,      variants[]{        colorName,        colorImage{          asset->{ _id, url }        },        stock,        sizes[]{          size,          stock        }      }    }
export type PRODUCTS_BY_CATEGORY_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  discountPercentage: number | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  variants: Array<{
    colorName: string | null;
    colorImage: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
    stock: number | null;
    sizes: Array<{
      size: string | null;
      stock: number | null;
    }> | null;
  }> | null;
}>;

// Source: ./sanity/lib/products/getProductBySlug.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug][0]{      _id,      name,      slug,      price,      discountPercentage,      description,      image,      variants[]{        colorName,        colorImage{          asset->{ _id, url }        },        stock,        sizes[]{          size,          stock        }      }    }
export type PRODUCT_BY_SLUG_QUERYResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  discountPercentage: number | null;
  description: BlockContent | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  variants: Array<{
    colorName: string | null;
    colorImage: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
    stock: number | null;
    sizes: Array<{
      size: string | null;
      stock: number | null;
    }> | null;
  }> | null;
} | null;

// Source: ./sanity/lib/products/searchProductsByColor.ts
// Variable: SEARCH_PRODUCTS_BY_COLOR_QUERY
// Query: *[    _type == "product" &&    count(      variants[        lower(string(colorName)) match $color      ]    ) > 0  ] | order(name asc)
export type SEARCH_PRODUCTS_BY_COLOR_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: BlockContent;
  price?: number;
  discountPercentage?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  variants?: Array<{
    colorName?: string;
    colorImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    stock?: number;
    sizes?: Array<{
      size?: string;
      stock?: number;
      _key: string;
    }>;
    _type: "colorVariant";
    _key: string;
  }>;
}>;

// Source: ./sanity/lib/products/searchProductsByName.ts
// Variable: PRODUCT_SEARCH_QUERY
// Query: *[_type == "product" &&  name match $searchParameter] | order(name asc)
export type PRODUCT_SEARCH_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: BlockContent;
  price?: number;
  discountPercentage?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  variants?: Array<{
    colorName?: string;
    colorImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    stock?: number;
    sizes?: Array<{
      size?: string;
      stock?: number;
      _key: string;
    }>;
    _type: "colorVariant";
    _key: string;
  }>;
}>;

// Source: ./sanity/lib/sales/getActiveSaleByCouponCode.ts
// Variable: ACTIVE_SALEBY_COUPON_QUERY
// Query: *[_type=="sale" && isActive==true && couponCode==$couponCode] | order(validFrom desc)[0]
export type ACTIVE_SALEBY_COUPON_QUERYResult = {
  _id: string;
  _type: "sale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  discountAmount?: number;
  couponCode?: string;
  validFrom?: string;
  validUntil?: string;
  isActive?: boolean;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n    *[_type == \"orders\" && clerkUserId == $userId]\n      | order(orderDate desc) {\n        _id,\n        orderNumber,\n        clerkUserId,\n        customerName,\n        email,\n        stripeCheckoutSessionId,\n        stripePaymentIntentId,\n        stripeCustomerId,\n        currency,\n        status,\n        totalPrice,\n        amountDiscount,\n        orderDate,\n  \n        shippingAddress {\n          fullName,\n          street1,\n          street2,\n          city,\n          state,\n          postalCode,\n          country,\n          phone\n        },\n  \n        products[] {\n          quantity,\n          selectedColor,\n          selectedSize,\n          product->{\n            _id,\n            name,\n            price,\n            image,\n            \"slug\": slug.current,\n            variants\n          }\n        }\n      }\n  ": MY_ORDERS_QUERYResult;
    "*[_type == \"category\"] | order(name asc)": ALL_CATEGORIES_QUERYResult;
    "\n    *[_type == \"product\"] | order(name asc){\n      _id,\n      name,\n      slug,\n      price,\n      discountPercentage,\n      image,\n      variants[]{\n        colorName,\n        colorImage{\n          asset->{ _id, url }\n        },\n        stock,\n        sizes[]{\n          size,\n          stock\n        }\n      }\n    }\n  ": ALL_PRODUCTS_QUERYResult;
    "\n    *[_type == \"product\" && references(*[_type == \"category\" && slug.current == $slug]._id)]\n    | order(name asc){\n      _id,\n      name,\n      slug,\n      price,\n      discountPercentage,\n      image,\n      variants[]{\n        colorName,\n        colorImage{\n          asset->{ _id, url }\n        },\n        stock,\n        sizes[]{\n          size,\n          stock\n        }\n      }\n    }\n  ": PRODUCTS_BY_CATEGORY_QUERYResult;
    "\n    *[_type == \"product\" && slug.current == $slug][0]{\n      _id,\n      name,\n      slug,\n      price,\n      discountPercentage,\n      description,\n      image,\n      variants[]{\n        colorName,\n        colorImage{\n          asset->{ _id, url }\n        },\n        stock,\n        sizes[]{\n          size,\n          stock\n        }\n      }\n    }\n  ": PRODUCT_BY_SLUG_QUERYResult;
    "\n  *[\n    _type == \"product\" &&\n    count(\n      variants[\n        lower(string(colorName)) match $color\n      ]\n    ) > 0\n  ] | order(name asc)\n": SEARCH_PRODUCTS_BY_COLOR_QUERYResult;
    "\n        *[_type == \"product\" &&  name match $searchParameter] | order(name asc)\n        ": PRODUCT_SEARCH_QUERYResult;
    "\n        *[_type==\"sale\" && isActive==true && couponCode==$couponCode] | order(validFrom desc)[0]": ACTIVE_SALEBY_COUPON_QUERYResult;
  }
}
