import type { Metadata } from "next";
import "../globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";
import { VisualEditing } from "next-sanity/visual-editing";
import { draftMode } from "next/headers";
import { DisableDraftMode } from "@/components/DisableDraftMode";

import { Quicksand } from "next/font/google";
import Footer from "@/components/Footer";
// import { get } from "http";
// import { getAllCategories } from "@/sanity/lib/products/getAllCategories";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const categories = await getAllCategories();
  return (
    <ClerkProvider dynamic>
      <html lang="en" className={quicksand.variable}>
        <body className="font-sans">
          {(await draftMode()).isEnabled && (
            <>
              <DisableDraftMode />
              <VisualEditing />
            </>
          )}

          <main>
            <Header />
            {children}
          </main>
          <footer>
            <Footer />  
          </footer>
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
